### ISSUE TITLE
Performance issues with update 7.11

### ISSUE THREAD

**Issue by slovvik** [newrelic/newrelic-java-agent#1135]
## Description
After upgrading newrelic to version 7.11 (from 7.10) we notice an increase in CPU usage percentage. To the point, an application was not able to run normally. CPU was used to perform GC-related tasks. It looks like some kind of memory leak.
Our apps are written in Scala and are based on cats-effect. It seems that [it PR](https://github.com/newrelic/newrelic-java-agent/pull/1006) introduces the problem. It also looks like the tracing is completely broken but this might be related to performance issues.

## Expected Behavior
No performance deterioration

## [Troubleshooting]
After turning off instrumentation for cats-effect there is no more problem with performance.
Example for cats-effect-2
```
# Custom parameters that disable automatic instrumentation for given libraries. Otherwise, tracing is completely broken and also performance suffers.
  class_transformer:
    com.newrelic.instrumentation.cats-effect-2:
      enabled: false
```

## Steps to Reproduce
Update newrelic agent from version 7.10 to version 7.11

## Your Environment
Arch | amd64
Java VM | OpenJDK 64-Bit Server VM
Java VM version | 11.0.15+10
Java vendor | Eclipse Adoptium
Java version | 11.0.15
Logical Processors | 4
OS | Linux
OS version | 4.14.301-224.520.amzn2.x86_64

## Additional context
Our service run on servlets. For this we are using http4s servlet support. Maybe that has an effect on the mentioned problem?
