### ISSUE TITLE
Doc improvement - better example(s) of yml config stanzas to environment variables

### ISSUE THREAD

**Issue by jtduffy** [newrelic/newrelic-java-agent#1449]
https://docs.newrelic.com/docs/apm/agents/java-agent/configuration/java-agent-configuration-config-file/#Environment_Variables

Add an example of a complicated yml config --> environment variable:
```
common:
  class_transformer:
    com.newrelic.instrumentation.kafka-clients-spans-0.11.0.0:
      enabled: true
```

Environment variable:
`NEW_RELIC_CLASS_TRANSFORMER_COM_NEWRELIC_INSTRUMENTATION_KAFKA_CLIENTS_SPANS_0_11_0_0_ENABLED`

There is also an outdated section that states that `For agent versions 4.10.0 or higher the following environment variables are available:` and then lists 5 variables.  This is incorrect since all config options are available as environment variables
