### ISSUE TITLE
Add local decorating support for Log4j2 when using JsonTemplateLayout

### ISSUE THREAD

**Issue by jasonjkeller** [newrelic/newrelic-java-agent#1730]
## Problem

The Java agent log4j2 instrumentation supports local decorating (aka adding linking metadata) of logs using `JsonLayout`. However, `JsonLayout` has been deprecated in favor of [JsonTemplateLayout](https://logging.apache.org/log4j/2.x/manual/json-template-layout.html) and the local decorating feature no longer works with this.

If possible, we should add support for local decorating of logs when using `JsonTemplateLayout`.

## Examples

If you create an appender using `JsonTemplateLayout` the logs don't get decorated with linking metadata:

```
	<Appenders>
		<Console name="Console" target="SYSTEM_OUT">
			<!-- THIS DOES NOT WORK! Use JsonTemplateLayout with default JsonLayout provided by log4j2 -->
                         <JsonTemplateLayout eventTemplateUri="classpath:JsonLayout.json"/>
		</Console>
	</Appenders>
```

Log:

```
{"instant":{"epochSecond":1707523057,"nanoOfSecond":137607000},"thread":"restartedMain","level":"INFO","loggerName":"org.springframework.samples.petclinic.PetClinicApplication","message":"No active profile set, falling back to default profiles: default","endOfBatch":false,"loggerFqcn":"org.apache.commons.logging.LogAdapter$Log4jLog","threadId":60,"threadPriority":5}
```

If you create an appender using `JsonLayout` the logs do get decorated with `NR-LINKING` metadata:

```
	<Appenders>
		<Console name="Console" target="SYSTEM_OUT">
			<!-- THIS WORKS! Use deprecated JsonLayout provided by log4j2 -->
                         <JsonLayout compact="true" />
		</Console>
	</Appenders>
```

Log:

```
{"instant":{"epochSecond":1707523091,"nanoOfSecond":992987000},"thread":"restartedMain","level":"INFO","loggerName":"org.springframework.samples.petclinic.PetClinicApplication","message":"No active profile set, falling back to default profiles: default NR-LINKING|ABCDEFGHIJKLMNOP|pksdfsdfsdfsdfmv0|||SpringBootPetClinic|","endOfBatch":false,"loggerFqcn":"org.apache.commons.logging.LogAdapter$Log4jLog","threadId":60,"threadPriority":5}
```

## Workaround

Workaround would be to use the deprecated `JsonLayout` until `JsonTemplateLayout` is fully supported. 

## Repro App

SpringBoot PetClinic app configured with log4j2 logging.

Build: `./mvnw package`

Run with the Java agent attached and the following agent config:

```
  application_logging:
    enabled: true
    forwarding:
      enabled: false
      max_samples_stored: 100000
      context_data:
        enabled: false
        # A comma separated list of attribute keys whose values should be sent to New Relic.
        #include:
        # A comma separated list of attribute keys whose values should not be sent to New Relic.
        #exclude:
    local_decorating:
      enabled: true
    metrics:
      enabled: true
```

The logging config can be found in `src/main/resources/log4j2-spring.xml` if you want to toggle between working/non-working Json layouts.

[spring-petclinic-JsonTemplateLayout.zip](https://github.com/newrelic/newrelic-java-agent/files/14227203/spring-petclinic-JsonTemplateLayout.zip)
