### ISSUE TITLE
[6.4.0 Agent Release] - Publicly document jar collector config

### ISSUE THREAD

**Issue by jasonjkeller** [newrelic/newrelic-java-agent#192]
This is dependent on https://github.com/newrelic/newrelic-java-agent/pull/183 being included in the 6.4.0 agent release and the artifact being published.

Along with this PR I think we should update the [public agent config doc](https://docs.newrelic.com/docs/agents/java-agent/configuration/java-agent-configuration-config-file#Error_Collector) to include a section on the `jar_collector` config options:

```
  jar_collector:
    enabled: true # default true
    max_class_loaders: 300 # default 5000
    skip_temp_jars: true # default true
    jars_per_second: 5 # default 10
```

It doesn't look like we publicly document any of these config settings.
