### ISSUE TITLE
AIT: fix capture artifact when multiple AITs fail

### ISSUE THREAD

**Issue by meiao** [newrelic/newrelic-java-agent#1987]
### Description
When an AIT fails, we capture some info about the test. This info is captured using the upload-artifact action.
The step that does it is:

```
      - name: Capture testing artifacts
        if: ${{ failure() || success() }}
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # pin@v4
        with:
          name: ${{ github.workflow }}-${{ github.job }}-${{ env.MATRIX }}
          path: |
            agent-integration-tests/testing-artifacts/*
```

But during execution, it looks like the name is not being properly populated.
![image](https://github.com/user-attachments/assets/d9a00781-eafe-43d8-8167-a931d0a39450)

`github.workflow` seems to resolve to `Test Suite - PR`, `github.job` to `tests`, but it looks like ${{env.MATRIX}} is not populating as we would expect.

### Acceptance Criteria
Captured test artifacts have the correct name, matching the test being run.
