### ISSUE TITLE
HTTP/2 support in AITs

### ISSUE THREAD

**Issue by jtduffy** [newrelic/newrelic-java-agent#2111]
Evaluate the existing AITs and see which ones would be candidates for adding coverage for HTTP/2 support.

List of HTTP/2 client and server frameworks:
https://docs.google.com/spreadsheets/d/150ntwH2aO9Sr6mg0lVVkNScmLKSJpxNZXhqAoTHKo5U/edit?gid=0#gid=0

## Enable HTTPS and HTTP/2 for Spring Boot 3 / Spring Framework 6 Apps

Generate a self signed localhost cert:
`-keystore keystore.p12 -storetype PKCS12 -storepass password -validity 9999`

This will create the keystore `keystore.p12` in the current folder. Copy this file into the 
`src/main/resources` folder of the application.

Update the `application.properties` or `application.yml` file to reference the keystore:
```
server.port=8443
server.http2.enabled=true
server.ssl.key-alias=localhost
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=password
server.ssl.key-store-type=PKCS12
```

```
server:
  port: 8443
  http2:
    enabled:true
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: localhost
```

This will start the app with HTTPS and HTTP/2 support listening on port 8443.
