### ISSUE TITLE
JBoss Wildfly throws error on startup

### ISSUE THREAD

**Issue by Steve24by7** [newrelic/newrelic-java-agent#229]
# Wildfly startup shows the following error when NewRelic is enabled
2016-11-29 10:50:04,223 ERROR [org.jboss.as.controller.management-operation] (New Relic Harvest Service) WFLYCTL0013: Operation ("read-attribute") failed - address: ([("subsystem" => "transactions")]) - failure description: "WFLYCTL0216: Management resource '[(\"subsystem\" => \"transactions\")]' not found"

Tracked in New Relic Ticket 437213

## Description
#  https://discuss.newrelic.com/t/wildfly-startup-throws-an-error-for-transactions-subsystem/44417 

## Expected Behavior
Startup with no console errors.

## Troubleshooting
In the previous cases, as an another workaround to ignore the message, we suggested to disable jboss-jmx-7 instrumentation as tracking through the source code, it does look like the jboss is part of the below instrumentation package:

com.newrelic.instrumentation.jboss-jmx-7

This does work, but has the unfortunate side-effect of losing jmx monitoring.

## Additional context

(Migrate to Jira)

**Comment by jasonchester** [comment]
The startup errors are causing the health endpoint to report as down in wildfly for us making this a blocking issue which we cannot ignore as we are using the health endpoint for our liveness checks.


```sh
❯ curl http://localhost:9990/health -sS | jq
```

```json
{
  "status": "DOWN",
  "checks": [
    {
      "name": "server-state",
      "status": "UP",
      "data": {
        "value": "running"
      }
    },
    {
      "name": "deployments-status",
      "status": "UP",
      "data": {
        "instant-impact-keycloak-bundle-1.0.0-SNAPSHOT.ear": "OK",
        "saml-group-idp-mapper-1.0.0-SNAPSHOT.jar": "OK",
        "client-management-keycloak-bundle-1.0.0-SNAPSHOT.ear": "OK",
        "keycloak-server.war": "OK",
        "set-existing-user-info-authenticator-1.0.0-SNAPSHOT.jar": "OK"
      }
    },
    {
      "name": "boot-errors",
      "status": "DOWN",
      "data": {
        "boot-errors": "[{\"failed-operation\" : {\"operation\" : \"read-attribute\", \"address\" : [{ \"subsystem\" : \"transactions\" }]}, \"failure-description\" : \"WFLYCTL0216: Management resource '[(\\\"subsystem\\\" => \\\"transactions\\\")]' not found\"},{\"failed-operation\" : {\"operation\" : \"read-attribute\", \"address\" : [{ \"subsystem\" : \"transactions\" }]}, \"failure-description\" : \"WFLYCTL0216: Management resource '[(\\\"subsystem\\\" => \\\"transactions\\\")]' not found\"},{\"failed-operation\" : {\"operation\" : \"read-attribute\", \"address\" : [{ \"subsystem\" : \"transactions\" }]}, \"failure-description\" : \"WFLYCTL0216: Management resource '[(\\\"subsystem\\\" => \\\"transactions\\\")]' not found\"},{\"failed-operation\" : {\"operation\" : \"read-attribute\", \"address\" : [{ \"subsystem\" : \"transactions\" }]}, \"failure-description\" : \"WFLYCTL0216: Management resource '[(\\\"subsystem\\\" => \\\"transactions\\\")]' not found\"},{\"failed-operation\" : {\"operation\" : \"read-attribute\", \"address\" : [{ \"subsystem\" : \"transactions\" }]}, \"failure-description\" : \"WFLYCTL0216: Management resource '[(\\\"subsystem\\\" => \\\"transactions\\\")]' not found\"},{\"failed-operation\" : {\"operation\" : \"read-attribute\", \"address\" : [{ \"subsystem\" : \"transactions\" }]}, \"failure-description\" : \"WFLYCTL0216: Management resource '[(\\\"subsystem\\\" => \\\"transactions\\\")]' not found\"},{\"failed-operation\" : {\"operation\" : \"read-attribute\", \"address\" : [{ \"subsystem\" : \"transactions\" }]}, \"failure-description\" : \"WFLYCTL0216: Management resource '[(\\\"subsystem\\\" => \\\"transactions\\\")]' not found\"},{\"failed-operation\" : {\"operation\" : \"read-attribute\", \"address\" : [{ \"subsystem\" : \"transactions\" }]}, \"failure-description\" : \"WFLYCTL0216: Management resource '[(\\\"subsystem\\\" => \\\"transactions\\\")]' not found\"},{\"failed-operation\" : {\"operation\" : \"read-attribute\", \"address\" : [{ \"subsystem\" : \"transactions\" }]}, \"failure-description\" : \"WFLYCTL0216: Management resource '[(\\\"subsystem\\\" => \\\"transactions\\\")]' not found\"},{\"failed-operation\" : {\"operation\" : \"read-attribute\", \"address\" : [{ \"subsystem\" : \"transactions\" }]}, \"failure-description\" : \"WFLYCTL0216: Management resource '[(\\\"subsystem\\\" => \\\"transactions\\\")]' not found\"}]"
      }
    },
    {
      "name": "ready-deployment.instant-impact-keycloak-bundle-1.0.0-SNAPSHOT.ear.com.brandmuscle.keycloak-instant-impact-user-storage-provider-1.0.0-SNAPSHOT.jar",
      "status": "UP"
    }
  ]
}
```

We have added the following to the newrelic.yml which removed the errors from the logs which fixes the health check reporting the startup errors but this is not the solution we want to use long term.

```yaml
common: &default_settings
# ...
  class_transformer:
# ...
    # this is being added to resolve startup errors
    # https://discuss.newrelic.com/t/wildfly-startup-throws-an-error-for-transactions-subsystem/44417/5
    # https://github.com/newrelic/newrelic-java-agent/issues/229
    com.newrelic.instrumentation.jboss-jmx-7: 
      enabled: false
# ...
```

**Comment by jasonchester** [comment]
Any update on this issue? It sucks that we have to disable JMX monitoring to use the new relic agent and have clean startup.

**Comment by jasonchester** [comment]
using version 7.1.1 on Wildfly 23.0.1 I had to also set the following in order to clean up boot errors.

```yaml
common: &default_settings
# ...
  class_transformer:
    # this is being added to resolve startup errors
    # https://discuss.newrelic.com/t/wildfly-startup-throws-an-error-for-transactions-subsystem/44417/5
    # https://github.com/newrelic/newrelic-java-agent/issues/229
    com.newrelic.instrumentation.jboss-jmx-7: 
      enabled: false
    com.newrelic.instrumentation.wildfly-jmx-14:
      enabled: false
```
