### ISSUE TITLE
[AIT] Improve test coverage for Netty involving HTTP2 edge cases

### ISSUE THREAD

**Issue by obenkenobi** [newrelic/newrelic-java-agent#2368]
### Description
In light of a recent [PR](https://github.com/newrelic/newrelic-java-agent/pull/2355), new tests for Netty (preferably AITs) should be added that address edge cases for HTTP2 calls. 

These include apps that make HTTP2 web requests and apps that use Http clients that call HTTP2 listeners within Netty. You can use a customer [sample app ](https://github.com/MT-Jacobs/sample-newrelic-kotlin-failure)to help build an AIT. 

### Acceptance Criteria

Tests need to address the following scenarios:

#### Http2 Web Transactions
Flipping the value of the config below should not affect wether HTTP2 web transactions are made
```
  netty:
    http2:
      frame_read_listener:
        start_transaction: false
```
#### Netty web transactions that uses a web client that makes calls to internal HTTP2 methods

Setting the below config to 'false' should make is so that 'unknown' transactions do not appear.
```
  netty:
    http2:
      frame_read_listener:
        start_transaction: false
```
Setting the above config to 'true' should make is so that 'unknown' transactions do appear.
