### ISSUE TITLE
[NR Distro OTel] Figure out how to get an OTel distro to report as an APM service entity type

### ISSUE THREAD

**Issue by jasonjkeller** [newrelic/newrelic-java-agent#2392]
There are two different APM entity types that agents will typically be associated with, `Services - APM` and `Services - OpenTelemetry`. In general, our existing APM Java agent will send data to `Services - APM` and other telemetry sources (e.g. OTel java agent, micrometer, etc) will send data to `Services - OpenTelemetry`. 

Note: `Services - OpenTelemetry` is an unfortunate misnomer as it really serves as a catch all for telemetry that doesn't come from a NR APM agent and doesn't necessarily have anything at all to do with OTel (e.g. the data could be coming from our Telemetry SDK).

That aside, the `Services - APM` entity type provides a much more polished and feature-rich UI and we would like for any OTel distro to light up this UI and be treated as a first class APM entity.

In part, this work will likely be blocked by https://github.com/newrelic/newrelic-java-agent/issues/2391, which is the work to get the distro to send data to NR agent collector endpoints. We should still be able to start looking into this though to determine what the requirements will be to get the data to be associated with a `Services - APM` entity.

**Comment by Newrelic-Boomi** [comment]
https://new-relic.atlassian.net/browse/NR-428350

**Comment by jasonjkeller** [comment]
Some informative docs on entities: 
https://github.com/newrelic/entity-definitions/blob/main/docs/entities/README.md
https://github.com/newrelic/entity-definitions/blob/main/docs/entities/synthesis.md

Entities do get synthesized based on the presence of specific telemetry. This is the definition/synthesis rules for an `EXT | SERVICE` entity type, which is what a `Services - OpenTelemetry` entity will be. https://github.com/newrelic/entity-definitions/blob/main/entity-types/ext-service/definition.yml

If I’m understanding correctly, then it’s basically the presence of the `service.name` attribute on telemetry data that causes it to match these synthesis rules. It then evaluates the related `conditions` that must match in order to produce an OTel entity. The `conditions` seem to be that the `instrumentation.provider` attribute exists with a value of `opentelemetry`, and the `newrelic.entity.type` and `trace_role` attributes don’t exist.

```
    # telemetry from opentelemetry provider
  - identifier: service.name
    name: service.name
    encodeIdentifierInGUID: true
    conditions:
    - attribute: instrumentation.provider
      value: opentelemetry
    - attribute: newrelic.entity.type
      present: false
    - attribute: trace_role
      present: false
    tags:
      k8s.cluster.name:
        ttl: P1D
      k8s.deployment.name:
        ttl: P1D
      k8s.namespace.name:
        ttl: P1D
      telemetry.sdk.language:
        entityTagName: language
      telemetry.sdk.version:
      service.namespace:
      faas.name:
      faas.id:
```

Here’s the synthesis rules for an `APM | APPLICATION` entity, which doesn’t seem very strict:
https://github.com/newrelic/entity-definitions/tree/main/entity-types/apm-application
