### ISSUE TITLE
Solr 8 JMX metrics enhancement

### ISSUE THREAD

**Issue by breedx-nr** [newrelic/newrelic-java-agent#78]
## TL;DR

When Solr8 is using cloud sharding, some of the JMX metrics are not reporting.  It would be great if they would!

## About

If we look in the [Solr7JmxValues.java](https://github.com/newrelic/newrelic-java-agent/blob/main/newrelic-agent/src/main/java/com/newrelic/agent/jmx/values/Solr7JmxValues.java) class we can see that the `updateHandler' is looking for beanName:
```
solr:dom1=core,dom2=*,category=UPDATE,scope=updateHandler,name=*
```
but when Solr is configured for sharding, [the names are dynamically generated](https://github.com/apache/lucene-solr/blob/bd8905150d6aabd3485874f52572279d9220a8c1/solr/core/src/java/org/apache/solr/metrics/reporters/jmx/JmxObjectNameFactory.java#L90) to an arbitrary depth, and may look more like this:
```
solr:dom1=core,dom2=solr-inventory,dom3=shard1,dom4=replica_n1,category=UPDATE,scope=updateHandler,name=adds
```
For caching, the NR Solr 7 jmx support is looking for 
```
solr:dom1=core,dom2=*,category=CACHE,scope=searcher,name=documentCache
```
but Solr8 might look more like 
```
solr:dom1=core,dom2=solr-inventory,dom3=shard1,dom4=replica_n1,category=CACHE,scope=searcher,name=documentCache
```
When the New Relic JMX component cannot find these beans, the data does not get reported and ends up showing up as zeros in the UI.

## Feature Description

The agent should be enhanced to be able to find the sharded JMX beans.  Rather than hard-coding a handful of fixed names, the agent should adapt to solr 8 and be able to list or otherwise enumerate the bean names and match the arbitrary-depth domain names, as shown above. 

These beans should be queried/monitored by the agent and reported to New Relic for display in the NR1 UI.

## Describe Alternatives

Solr uses [dropwizard/codahale metrics](https://lucene.apache.org/solr/guide/8_6/metrics-reporting.html) internally, and so the [New Relic dropwizard reporter](https://github.com/newrelic/dropwizard-metrics-newrelic) might be able to be used to get the same telemetry.  Some experimentation/exploration would be required to verify that the same information can be obtained...and also how it might map to a cohesive user experience.

## Additional context

It is unknown what earliest version of Solr supports cloud/shard bean names with arbitrary domain depth.  It _is_ likely that this will continue in future versions of dropwizard.

## Priority

"Really Want".  More than one customer has asked for this support.

**Comment by kford-newrelic** [comment]
Reviewed and determined to be permanently deferred.

**Comment by mmulligan03** [comment]
@rahmnathan I had to create a custom NR extension for SolrCloud caches and updates. 

Create a file called `newrelic-solr-extension.yml` in `/opt/newrelic/extensions/` 

This is what I had in my file (not sure if it can be paired down at all) and they are all queryable via the Metrics table in NRQL:
```
name: SolrCloudCustom
version: 1.0
enabled: true
jmx:
  - object_name: solr:dom1=core,dom2=*,dom3=*,dom4=*,category=CACHE,scope=searcher,name=*
    metrics:
      - attributes: inserts, hits, size, ramBytesUsed, lookups, hitratio, evictions, warmupTime
        type: simple
  - object_name: solr:dom1=core,dom2=*,dom3=*,dom4=*,category=UPDATE,scope=updateHandler,name=*
    metrics:
      - attributes: Value
        type: simple
  - object_name: solr:dom1=node,category=UPDATE,scope=updateShardHandler,name=*
    metrics:
      - attributes: Count, Max, Mean, Min, StdDev, MeanRate, 50thPercentile, 95thPercentile, 98thPercentile, 99thPercentile, 999thPercentile, OneMinuteRate, FiveMinuteRate, FifteenMinuteRate
        type: simple
  - object_name: solr:dom1=core,dom2=*,dom3=*,dom4=*,category=INDEX,name=sizeInBytes
    metrics:
      - attributes: Value
        type: simple
  - object_name: solr:dom1=core,dom2=*,dom3=*,dom4=*,category=QUERY,scope=/select,name=*
    metrics:
      - attributes: Count, Max, Mean, Min, StdDev, MeanRate, 50thPercentile, 95thPercentile, 98thPercentile, 99thPercentile, 999thPercentile, OneMinuteRate, FiveMinuteRate, FifteenMinuteRate
        type: simple
  - object_name: solr:dom1=core,dom2=*,dom3=*,dom4=*,category=QUERY,scope=/get,name=*
    metrics:
      - attributes: Count, Max, Mean, Min, StdDev, MeanRate, 50thPercentile, 95thPercentile, 98thPercentile, 99thPercentile, 999thPercentile, OneMinuteRate, FiveMinuteRate, FifteenMinuteRate
        type: simple
  - object_name: solr:dom1=core,dom2=*,dom3=*,dom4=*,category=SEARCHER,scope=*,name=*
    metrics:
      - attributes: Count, Value
        type: simple
```
