### ISSUE TITLE
Memory Heap issue with ning instrumentation

### ISSUE THREAD

**Issue by twcrone** [newrelic/newrelic-java-agent#783]
A Java app that runs with multiple JVM allocations in PROD is consistently reaching max memory heap usage, causing the instances to fail.  It appears that some of our `ning` instrumentation might be the culprit.

https://newrelic.atlassian.net/browse/GTSE-13769
https://newrelic.atlassian.net/browse/GTSE-14104

(Migrate to Jira)

**Comment by jasonjkeller** [comment]
We suspect that this was introduced in agent 7.5.0 either due to changes to the [Caffeine caching library](https://github.com/newrelic/newrelic-java-agent/pull/593) used by the agent or some changes to the [ning-async-http-client instrumentation](https://github.com/newrelic/newrelic-java-agent/pull/513).

For now the issue can be worked around by disabling the `ning-async-http-client` instrumentation by adding the following under the pre-existing `class_transformer` stanza in the agent yaml:

```
  class_transformer:
    com.newrelic.instrumentation.ning-async-http-client-1.0:
      enabled: false
    com.newrelic.instrumentation.ning-async-http-client-1.1:
      enabled: false
    com.newrelic.instrumentation.ning-async-http-client-1.6.1:
      enabled: false
```
